name: Daily Deploy to Coolify

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC (midnight). Adjust as needed (e.g., '0 12 * * *' for noon).

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify Deployment
        run: |
          curl --request GET "${{ secrets.COOLIFY_WEBHOOK }}" \
               --header "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}" \
               --fail  # Fail the job if the request errors out
