name: Coolify Daily Deploy

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC (8:00 AM HKT)
  workflow_dispatch:  # Adds manual trigger option

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify Deployment
        run: |
          curl --request GET "${{ secrets.COOLIFY_WEBHOOK }}" \
               --header "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}" \
               --fail
